
from django.contrib import admin
from django.urls import path
from .import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('login',views.login,name='login'),
    path('log',views.log,name='log'),
    path('home',views.home,name='home'),
    path('adminhome', views.adminhome, name='adminhome'),
    path('ureg',views.ureg,name='ureg'),
    path('reg',views.reg,name='reg'),
    path('uhome',views.uhome,name='uhome'),
    path('viewstaffuser',views.viewstaffuser,name='viewstaffuser'),
    path('vieweachstaffdetailsuser',views.vieweachstaffdetailsuser,name='vieweachstaffdetailsuser'),
    path('viewuser',views.viewuser,name='viewuser'),
    path('viewschemeuser',views.viewschemeuser,name='viewschemeuser'),
    path('apply',views.apply,name='apply'),
    path('applyscheme', views.applyscheme, name='applyscheme'),
    path('applyschemea', views.applyschemea, name='applyschemea'),
    path('addapplication',views.addapplication,name='addapplication'),
    path('approveapplication',views.approveapplication,name='approveapplication'),
    path('addstaff',views.addstaff,name='addstaff'),
    path('edit',views.edit,name='edit'),
    path('update',views.update,name='update'),
    path('staffd',views.staffd,name='staffd'),
    path('viewstaff',views.viewstaff,name='viewstaff'),
    path('vieweachstaffdetails',views.vieweachstaffdetails,name='vieweachstaffdetails'),
    path('gramapanchayat',views.gramapanchayat,name='gramapanchayat'),
    path('chakkupallamgp',views.chakkupallamgp,name='chakkupallamgp'),
    path('addgramasabha',views.addgramasabha,name='addgramasabha'),
    path('grama',views.grama,name='grama'),
    path('viewgramasabha',views.viewgramasabha,name='viewgramasabha'),
    path('editgramasabha',views.editgramasabha,name='editgramasabha'),
    path('updategramasabha',views.updategramasabha,name='updategramasabha'),
    path('addscheme',views.addscheme,name='addscheme'),
    path('scheme',views.scheme,name='scheme'),
    path('viewscheme',views.viewscheme,name='viewscheme'),
    path('editscheme',views.editscheme,name='editscheme'),
    path('updatescheme',views.updatescheme,name='updatescheme'),
    path('report',views.report,name='report'),
    path('schemewiseappli',views.schemewiseappli,name='schemewiseappli'),
    path('showschemewiseuser',views.showschemewiseuser,name='showschemewiseuser'),
    path('userwiseappli',views.userwiseappli,name='userwiseappli'),
    path('approvedappli',views.approvedappli,name='approvedappli'),
    path('rejectedappli',views.rejectedappli,name='rejectedappli'),
    path('search',views.search,name='search'),
    path('sear',views.sear,name='sear'),
    path('myprofile',views.myprofile,name='myprofile'),
    path('logout',views.logout,name='logout'),
    path('remove',views.remove,name='remove'),
    path('reject',views.reject,name='reject'),
    path('status',views.status,name='status'),

]
