# Generated by Django 3.2 on 2021-04-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('caste', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30)),
                ('wardno', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('cpass', models.CharField(max_length=30)),
            ],
        ),
    ]
