# Generated by Django 3.2 on 2021-04-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0002_auto_20210408_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='sex',
            new_name='sexx',
        ),
    ]
