# Generated by Django 3.2 on 2021-04-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0005_rename_name_staff_staffname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staffname',
            new_name='sname',
        ),
    ]
