# Generated by Django 3.2 on 2021-04-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0006_rename_staffname_staff_sname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='sname',
            new_name='staff',
        ),
    ]
