# Generated by Django 3.2 on 2021-04-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0007_rename_sname_staff_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff',
            new_name='stafname',
        ),
    ]
