# Generated by Django 3.2 on 2021-04-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0008_rename_staff_staff_stafname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='stafname',
            new_name='staffname',
        ),
    ]
