# Generated by Django 3.2 on 2021-04-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0009_rename_stafname_staff_staffname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staffname',
            new_name='fname',
        ),
    ]
