# Generated by Django 3.2 on 2021-04-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0010_rename_staffname_staff_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='fname',
            new_name='f1name',
        ),
    ]
