# Generated by Django 3.2 on 2021-04-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0011_rename_fname_staff_f1name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='f1name',
        ),
    ]
