# Generated by Django 3.2 on 2021-04-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0012_remove_staff_f1name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='f1name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
