# Generated by Django 3.2 on 2021-04-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0013_staff_f1name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='f1name',
            new_name='name',
        ),
    ]
