# Generated by Django 3.2 on 2021-04-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0014_rename_f1name_staff_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='contact',
            new_name='phone',
        ),
    ]
