# Generated by Django 3.2 on 2021-04-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0015_rename_contact_staff_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gramasabha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('wardno', models.CharField(max_length=30)),
            ],
        ),
    ]
