# Generated by Django 3.2 on 2021-04-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0017_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
