# Generated by Django 3.2 on 2021-04-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0020_auto_20210412_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='sexx',
            new_name='sex',
        ),
    ]
