# Generated by Django 3.2 on 2021-04-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0021_rename_sexx_userreg_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
