# Generated by Django 3.2 on 2021-04-22 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0023_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='schemeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panchayat.scheme'),
        ),
    ]
