# Generated by Django 3.2 on 2021-04-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0024_alter_application_schemeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='data',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='castep',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='idcardp',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='incomep',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='residencep',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='taxp',
            field=models.FileField(upload_to=''),
        ),
    ]
