# Generated by Django 3.2 on 2021-04-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0025_auto_20210423_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='data',
        ),
    ]
