# Generated by Django 3.2 on 2021-04-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0026_remove_application_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
