# Generated by Django 3.2.3 on 2021-06-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0029_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
